{
 "title": "Bitaxe ESP32-Miner Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(espminer_build_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Coinbase value in sats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "espminer_coinbase_value_total_satoshis{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} coinbase total value in stats"
    },
    {
     "expr": "espminer_coinbase_value_user_satoshis{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} coinbase user value in stats"
    }
   ]
  },
  {
   "title": "User % Coinbase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(espminer_coinbase_value_user_satoshis{instance=~\"${hostname}\"} / espminer_coinbase_value_total_satoshis{instance=~\"${hostname}\"}) * 100",
     "legendFormat": "{{instance}} coinbase user value %"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "espminer_voltage_volts{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - volts"
    },
    {
     "expr": "espminer_core_voltage_mv{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - mv"
    },
    {
     "expr": "espminer_frequency_hz{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - frequency_hz"
    },
    {
     "expr": "espminer_power_watts{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - power_watts"
    },
    {
     "expr": "espminer_current_amps{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - current_amps"
    }
   ]
  },
  {
   "title": "Wifi",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "wifi",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "espminer_wifi_rssi_dbm{instance=~\"${hostname}\"}",
       "legendFormat": "{{instance}} - wifi rssi dbm"
      },
      {
       "expr": "espminer_wifi_connected{instance=~\"${hostname}\"}",
       "legendFormat": "{{instance}} - wifi rssi dbm"
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "espminer_heap_free_bytes{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - heap free"
    },
    {
     "expr": "espminer_heap_min_free_bytes{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - heap min free"
    },
    {
     "expr": "espminer_heap_free_spiram_bytes{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - heap spiram"
    }
   ]
  },
  {
   "title": "heap free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "espminer_heap_free_internal_bytes{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - heap free"
    }
   ]
  },
  {
   "title": "cpu usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "espminer_cpu_usage_percent{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - cpu usage %"
    }
   ]
  },
  { "title": "Fans", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Fan speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "espminer_fan_rpm{instance=~\"${hostname}\",fan=\"1\"}",
     "legendFormat": "{{instance}} fan rpm"
    },
    {
     "expr": "espminer_fan_rpm{instance=~\"${hostname}\",fan=\"2\"}",
     "legendFormat": "{{instance}} fan2 rpm"
    }
   ]
  },
  {
   "title": "Fan speed %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "espminer_fan_speed_percent{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} fan rpm"
    }
   ]
  },
  { "title": "Hashing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Hashrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "espminer_hashrate_hashes_per_second{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - instant"
    },
    {
     "expr": "espminer_hashrate_1m{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - 1m"
    },
    {
     "expr": "espminer_hashrate_10m{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - 10m"
    },
    {
     "expr": "espminer_hashrate_1h{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - 1h"
    },
    {
     "expr": "espminer_expected_hashrate{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - expected hashrate"
    },
    {
     "expr": "sum by(instance) (espminer_asic_hashrate{instance=~\"${hostname}\"})",
     "legendFormat": "{{instance}} - hashrate"
    }
   ]
  },
  {
   "title": "Hashrate by asic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "avg by(asic, instance) (espminer_asic_domain_hashrate{instance=~\"${hostname}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shares",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "rate(espminer_shares_accepted_total{instance=~\"${hostname}\"}[5m]) * 60",
     "legendFormat": "{{instance}} - accepted"
    },
    {
     "expr": "rate(espminer_shares_rejected_total{instance=~\"${hostname}\"}[5m]) * 60",
     "legendFormat": "{{instance}} - rejected"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "espminer_error_percentage{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} instant"
    },
    {
     "expr": "\navg by(instance) (\n  avg_over_time(\n    espminer_error_percentage{instance=~\"${hostname}\"}[20m]\n  )\n)",
     "legendFormat": "{{label_name}} 20m"
    }
   ]
  },
  {
   "title": "Best Share",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "espminer_best_share{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - all time best share"
    },
    {
     "expr": "espminer_best_session_share{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - session best"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "rate(espminer_jobs_received_total{instance=~\"${hostname}\"}[5m])",
     "legendFormat": "{{instance}} - jobs recieved"
    }
   ]
  },
  { "title": "Difficulty", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Block height",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "espminer_block_height{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - block height"
    }
   ]
  },
  {
   "title": "Network difficulty",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "espminer_network_difficulty{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - network difficulty"
    }
   ]
  },
  {
   "title": "Pool difficulty",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "espminer_pool_difficulty{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - pool difficulty"
    },
    {
     "expr": "avg by(instance) (\n  avg_over_time(\n    espminer_pool_difficulty{instance=~\"${hostname}\"}[10h]\n  )\n)",
     "legendFormat": "{{instance}} - 30m"
    }
   ]
  },
  { "title": "Temps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "espminer_chip_temp_celsius{instance=~\"${hostname}\",chip=\"1\"}",
     "legendFormat": "{{instance}} - chip temp"
    },
    {
     "expr": "espminer_chip_temp_celsius{instance=~\"${hostname}\",chip=\"2\"}",
     "legendFormat": "{{instance}} - chip temp2"
    },
    {
     "expr": "espminer_vr_temp_celsius{instance=~\"${hostname}\"}",
     "legendFormat": "{{instance}} - vr temp"
    }
   ]
  }
 ]
}